update hardcoded paths to 2016
cp3-llbb/HHAnalysis pull request #107
Opened 2016-10-20 10:26 UTC by OlivierBondu

should be painless

yet to do:
- [ ] assess efficiency for the various datasets on runs < 274094

2016-10-21 15:36 UTC, OlivierBondu commented
Efficiency for Double Mu on Run2016B is 99.6602%, looking good

2016-10-25 21:15 UTC, blinkseb requested changes

2016-10-25 21:15 UTC, blinkseb commented on plugins/Categories.cc
> +        if (path.find("HLT_Mu") != std::string::npos) manager.pass_cut("fire_trigger_MuMu");
This condition is also true for MuEl paths, which mean an event will be in two categories at the same time (not sure it's possible?). It'd probably be easier to use a regex here, something like `HLT_Mu.*_Mu`

2016-11-04 17:31 UTC, blinkseb approved these changes

2016-11-04 17:32 UTC, blinkseb commented
I updated the PR using regex to match trigger paths.

2016-11-06 15:03 UTC, blinkseb commented
PR updated. I added support for multiple efficiency for a given HLT path / leg (like Double Mu ones). Luminosity values in the python config files are not the correct ones and must be updated.

For a given path, you can now specify more than one JSON file. Each file is assigned a weight. This weight will be used to create a discrete probability function, where each path is assigned the probability `weight / ∑(weights)`. When requesting an efficiency, one is chose randomly based on this distribution.

2016-11-07 13:21 UTC, BrieucF commented
:+1:  with moving the modifications to `triggers.xml` in this PR.

2016-11-07 13:39 UTC, blinkseb commented
`triggers.xml` added. Merging!

2016-11-07 13:39 UTC, merged

2016-11-11 02:15 UTC, OlivierBondu commented
thanks !